### PR TITLE
[#28] roundTripsCanonicalJsonPretty: Use Either type, not panic

### LINKED ISSUE #28: `roundTripsCanonicalJsonPretty` uses `panic` which Hedgehog doesn't like
[This use of `panic`](https://github.com/input-output-hk/cardano-prelude/blob/188a2abcc6a065fed4e8cdd63e1e7c3f9d57d05a/test/Test/Cardano/Prelude/Tripping.hs#L78) causes Hedgehog to be hit with an asyc FatalError exception, which seems to cause it to abort error message printout. So we don't get our nice roundtrip error messages.

### PR DESCRIPTION
**Pull request by mhuesch**
Closes #28.

### CODE REVIEW

File: test/Test/Cardano/Prelude/Tripping.hs [hunk 1]
```diff
@@ -72,11 +72,13 @@ roundTripsCanonicalJsonPretty a = tripping a canonicalEncPre canonicalDecPre
...
-    CanonicalJSON.fromJSON
-      $ either (panic . toS) identity
-      $ CanonicalJSON.parseCanonicalJSON y
+    -> Either Text a
+  canonicalDecPre y = do
+    eVal <- transformLeft toS (CanonicalJSON.parseCanonicalJSON y)
+    transformLeft show (CanonicalJSON.fromJSON eVal :: Either SchemaError a)
+
+transformLeft :: (a -> c) -> Either a b -> Either c b
+transformLeft f = either (Left . f) Right
```
Comment (Jimbo4350) [inline test/Test/Cardano/Prelude/Tripping.hs]: Definitely an improvement!

**Comment by mhuesch** [comment]
Before merging, I switched to using `first` from bifunctor, as @erikd suggested [here](https://github.com/input-output-hk/cardano-prelude/commit/0821ee4c73841c9bac9bdc4f7e92a76f70ac144f#r32207420).
